version: '3.2'
services:
  mongo:
    image: dataglitter/mongo:3.4
    volumes:
      - dataglitter-data:/home/app/data
    ports:
      - "27017:27017"
#   post-service:
#     image: test-post-service
#     ports:
#       - "11012:8443"
#     environment:
#       - MONGO=mongo
#       - KEY_STORE_PASSWORD=${KEY_STORE_PASSWORD}
#       - KEY_PASSWORD=${KEY_PASSWORD}
#       - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
#       - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
#       - AWS_S3_ASSETBUCKETNAME=${DEV_ASSETS_BUCKET}
#       - JWT_SECRET=${JWT_SECRET}
#     depends_on:
#       - mongo

volumes:
  dataglitter-data:
